# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html
  configuration: reductionml-python/docs/source/conf.py
  fail_on_warning: true

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
    rust: "1.70"

python:
  install:
    - method: pip
      path: reductionml-python/

conda:
  environment: reductionml-python/docs/environment.yml
